export const MOCK_TRUMP_MENTIONS = [
  {
    id: 'mock_m1',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    ticker: 'AAPL',
    company_name: 'Apple Inc',
    sector: 'Technology',
    sentiment: 'positive',
    mention_type: 'investment_announcement',
    trump_quote:
      '...Just spoke with Tim Cook of Apple. They are investing 500 BILLION DOLLARS in America. Great company, great leader!...',
    context: 'Trump referenced Apple Inc positively in this statement',
    confidence: 0.92,
    market_impact_likely: 1,
    source_type: 'truth_social',
    source_url: 'https://truthsocial.com/@realDonaldTrump/123456789',
    source_title: 'Truth Social — @realDonaldTrump',
    posted_at: new Date(Date.now() - 3600000).toISOString(),
    price_at_mention: 198.45,
    price_1h_after: 199.12,
    price_24h_after: 201.33,
    pct_move_1h: 0.34,
    pct_move_24h: 1.45,
    source_post_id: 'mock_ts_1_AAPL',
  },
  {
    id: 'mock_m2',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    ticker: 'BA',
    company_name: 'Boeing Co',
    sector: 'Industrial',
    sentiment: 'negative',
    mention_type: 'direct_criticism',
    trump_quote:
      '...Boeing is making terrible planes. Unsafe. We are looking into it very seriously. Sad!...',
    context: 'Trump referenced Boeing Co negatively in this statement',
    confidence: 0.85,
    market_impact_likely: 1,
    source_type: 'truth_social',
    source_url: 'https://truthsocial.com/@realDonaldTrump/123456790',
    source_title: 'Truth Social — @realDonaldTrump',
    posted_at: new Date(Date.now() - 7200000).toISOString(),
    price_at_mention: 178.2,
    price_1h_after: 175.8,
    price_24h_after: 172.5,
    pct_move_1h: -1.35,
    pct_move_24h: -3.2,
    source_post_id: 'mock_ts_2_BA',
  },
  {
    id: 'mock_m3',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    ticker: 'X',
    company_name: 'U.S. Steel Corp',
    sector: 'Industrial',
    sentiment: 'positive',
    mention_type: 'policy_related',
    trump_quote:
      '...American Steel is coming back STRONG. We will protect our steel industry with tariffs. US Steel will be great again!...',
    context: 'Trump referenced U.S. Steel Corp positively in this statement',
    confidence: 0.85,
    market_impact_likely: 1,
    source_type: 'truth_social',
    source_url: 'https://truthsocial.com/@realDonaldTrump/123456791',
    source_title: 'Truth Social — @realDonaldTrump',
    posted_at: new Date(Date.now() - 10800000).toISOString(),
    price_at_mention: 42.15,
    price_1h_after: 43.8,
    price_24h_after: 45.2,
    pct_move_1h: 3.91,
    pct_move_24h: 7.24,
    source_post_id: 'mock_ts_3_X',
  },
  {
    id: 'mock_m4',
    created_at: new Date(Date.now() - 43200000).toISOString(),
    ticker: 'NVDA',
    company_name: 'NVIDIA Corp',
    sector: 'Technology',
    sentiment: 'positive',
    mention_type: 'direct_praise',
    trump_quote:
      'Trump says Nvidia chips critical to US AI dominance, calls Jensen Huang a great American businessman.',
    context: 'Trump referenced NVIDIA Corp positively in this statement',
    confidence: 0.92,
    market_impact_likely: 0,
    source_type: 'reuters_ap',
    source_url: 'https://www.reuters.com/technology/trump-nvidia-ai-chips-2026-06-01/',
    source_title: 'Reuters — Trump praises Nvidia',
    posted_at: new Date(Date.now() - 43200000).toISOString(),
    price_at_mention: 1180.5,
    price_1h_after: 1185.2,
    price_24h_after: 1192.8,
    pct_move_1h: 0.4,
    pct_move_24h: 1.04,
    source_post_id: 'mock_rt_1_NVDA',
  },
  {
    id: 'mock_m5',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    ticker: 'F',
    company_name: 'Ford Motor Company',
    sector: 'Industrial',
    sentiment: 'positive',
    mention_type: 'investment_announcement',
    trump_quote:
      '...Ford Motor Company announced 8 billion dollar investment in Michigan manufacturing plants. Tremendous for American workers!...',
    context: 'Trump referenced Ford Motor Company positively in this statement',
    confidence: 0.92,
    market_impact_likely: 1,
    source_type: 'whitehouse_remarks',
    source_url: 'https://www.whitehouse.gov/remarks/2026/06/01/investment-act-signing/',
    source_title: 'Remarks — White House',
    posted_at: new Date(Date.now() - 86400000).toISOString(),
    price_at_mention: 11.85,
    price_1h_after: 12.1,
    price_24h_after: 12.45,
    pct_move_1h: 2.11,
    pct_move_24h: 5.06,
    source_post_id: 'mock_wh_1_F',
  },
  {
    id: 'mock_m6',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    ticker: 'TSLA',
    company_name: 'Tesla Inc',
    sector: 'Technology',
    sentiment: 'positive',
    mention_type: 'direct_praise',
    trump_quote:
      '...Elon Musk is doing an incredible job with Tesla. Electric cars made in America. Winning!...',
    context: 'Trump referenced Tesla Inc positively in this statement',
    confidence: 0.85,
    market_impact_likely: 0,
    source_type: 'truth_social',
    source_url: 'https://truthsocial.com/@realDonaldTrump/123456792',
    source_title: 'Truth Social — @realDonaldTrump',
    posted_at: new Date(Date.now() - 172800000).toISOString(),
    price_at_mention: 245.3,
    price_1h_after: 248.1,
    price_24h_after: 252.6,
    pct_move_1h: 1.14,
    pct_move_24h: 2.98,
    source_post_id: 'mock_ts_4_TSLA',
  },
  {
    id: 'mock_m7',
    created_at: new Date(Date.now() - 259200000).toISOString(),
    ticker: 'XOM',
    company_name: 'ExxonMobil',
    sector: 'Energy',
    sentiment: 'positive',
    mention_type: 'policy_related',
    trump_quote:
      '...Energy companies like Exxon are drilling again. American energy dominance. Drill baby drill!...',
    context: 'Trump referenced ExxonMobil positively in this statement',
    confidence: 0.78,
    market_impact_likely: 1,
    source_type: 'financial_news',
    source_url: 'https://finance.yahoo.com/news/trump-energy-policy-exxon-2026-05-28.html',
    source_title: 'Yahoo Finance',
    posted_at: new Date(Date.now() - 259200000).toISOString(),
    price_at_mention: 108.4,
    price_1h_after: 109.2,
    price_24h_after: 110.8,
    pct_move_1h: 0.74,
    pct_move_24h: 2.21,
    source_post_id: 'mock_yf_1_XOM',
  },
  {
    id: 'mock_m8',
    created_at: new Date(Date.now() - 345600000).toISOString(),
    ticker: 'JPM',
    company_name: 'JPMorgan Chase',
    sector: 'Finance',
    sentiment: 'neutral',
    mention_type: 'indirect',
    trump_quote:
      '...Met with Jamie Dimon and leaders from JPMorgan Chase to discuss banking regulations and lending standards...',
    context: 'Trump referenced JPMorgan Chase neutrally in this statement',
    confidence: 0.85,
    market_impact_likely: 0,
    source_type: 'whitehouse_remarks',
    source_url: 'https://www.whitehouse.gov/remarks/2026/05/27/banking-roundtable/',
    source_title: 'Remarks — White House',
    posted_at: new Date(Date.now() - 345600000).toISOString(),
    price_at_mention: 198.7,
    price_1h_after: 198.5,
    price_24h_after: 199.1,
    pct_move_1h: -0.1,
    pct_move_24h: 0.2,
    source_post_id: 'mock_wh_2_JPM',
  },
  {
    id: 'mock_m9',
    created_at: new Date(Date.now() - 432000000).toISOString(),
    ticker: 'DIS',
    company_name: 'Walt Disney Co',
    sector: 'Consumer',
    sentiment: 'negative',
    mention_type: 'direct_criticism',
    trump_quote:
      '...Disney is woke and failing. They need to get back to what made them great. Very sad situation!...',
    context: 'Trump referenced Walt Disney Co negatively in this statement',
    confidence: 0.78,
    market_impact_likely: 0,
    source_type: 'truth_social',
    source_url: 'https://truthsocial.com/@realDonaldTrump/123456793',
    source_title: 'Truth Social — @realDonaldTrump',
    posted_at: new Date(Date.now() - 432000000).toISOString(),
    price_at_mention: 112.3,
    price_1h_after: 111.5,
    price_24h_after: 110.8,
    pct_move_1h: -0.71,
    pct_move_24h: -1.34,
    source_post_id: 'mock_ts_5_DIS',
  },
  {
    id: 'mock_m10',
    created_at: new Date(Date.now() - 518400000).toISOString(),
    ticker: 'SLX',
    company_name: 'Steel ETF',
    sector: 'Industrial',
    sentiment: 'positive',
    mention_type: 'policy_related',
    trump_quote:
      '...Steel tariffs will protect the American steel industry. Steel companies will thrive like never before!...',
    context: 'Trump referenced Steel ETF positively in this statement',
    confidence: 0.92,
    market_impact_likely: 1,
    source_type: 'financial_news',
    source_url: 'https://www.marketwatch.com/story/trump-steel-tariffs-2026-05-25',
    source_title: 'MarketWatch',
    posted_at: new Date(Date.now() - 518400000).toISOString(),
    price_at_mention: 58.2,
    price_1h_after: 59.1,
    price_24h_after: 60.4,
    pct_move_1h: 1.55,
    pct_move_24h: 3.78,
    source_post_id: 'mock_mw_1_SLX',
  },
]

export const MOCK_WATCHLIST = [
  {
    ticker: 'AAPL',
    company_name: 'Apple Inc',
    sector: 'Technology',
    total_mentions: 12,
    positive_count: 10,
    negative_count: 1,
    neutral_count: 1,
    avg_confidence: 0.89,
    avg_24h_move: 1.45,
    avg_1h_move: 0.34,
    last_mentioned_at: new Date(Date.now() - 3600000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 2592000000).toISOString(),
    ever_market_moving: 1,
  },
  {
    ticker: 'BA',
    company_name: 'Boeing Co',
    sector: 'Industrial',
    total_mentions: 8,
    positive_count: 2,
    negative_count: 5,
    neutral_count: 1,
    avg_confidence: 0.84,
    avg_24h_move: -2.1,
    avg_1h_move: -1.2,
    last_mentioned_at: new Date(Date.now() - 7200000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 5184000000).toISOString(),
    ever_market_moving: 1,
  },
  {
    ticker: 'NVDA',
    company_name: 'NVIDIA Corp',
    sector: 'Technology',
    total_mentions: 7,
    positive_count: 6,
    negative_count: 0,
    neutral_count: 1,
    avg_confidence: 0.88,
    avg_24h_move: 2.3,
    avg_1h_move: 0.8,
    last_mentioned_at: new Date(Date.now() - 43200000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 7776000000).toISOString(),
    ever_market_moving: 1,
  },
  {
    ticker: 'X',
    company_name: 'U.S. Steel Corp',
    sector: 'Industrial',
    total_mentions: 6,
    positive_count: 5,
    negative_count: 0,
    neutral_count: 1,
    avg_confidence: 0.86,
    avg_24h_move: 5.2,
    avg_1h_move: 2.8,
    last_mentioned_at: new Date(Date.now() - 10800000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 6048000000).toISOString(),
    ever_market_moving: 1,
  },
  {
    ticker: 'TSLA',
    company_name: 'Tesla Inc',
    sector: 'Technology',
    total_mentions: 5,
    positive_count: 3,
    negative_count: 1,
    neutral_count: 1,
    avg_confidence: 0.82,
    avg_24h_move: 1.8,
    avg_1h_move: 0.5,
    last_mentioned_at: new Date(Date.now() - 172800000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 8640000000).toISOString(),
    ever_market_moving: 0,
  },
  {
    ticker: 'F',
    company_name: 'Ford Motor Company',
    sector: 'Industrial',
    total_mentions: 4,
    positive_count: 4,
    negative_count: 0,
    neutral_count: 0,
    avg_confidence: 0.9,
    avg_24h_move: 4.5,
    avg_1h_move: 1.9,
    last_mentioned_at: new Date(Date.now() - 86400000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 9504000000).toISOString(),
    ever_market_moving: 1,
  },
  {
    ticker: 'XOM',
    company_name: 'ExxonMobil',
    sector: 'Energy',
    total_mentions: 4,
    positive_count: 3,
    negative_count: 0,
    neutral_count: 1,
    avg_confidence: 0.79,
    avg_24h_move: 1.5,
    avg_1h_move: 0.6,
    last_mentioned_at: new Date(Date.now() - 259200000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 10368000000).toISOString(),
    ever_market_moving: 1,
  },
  {
    ticker: 'SLX',
    company_name: 'Steel ETF',
    sector: 'Industrial',
    total_mentions: 3,
    positive_count: 3,
    negative_count: 0,
    neutral_count: 0,
    avg_confidence: 0.91,
    avg_24h_move: 3.2,
    avg_1h_move: 1.4,
    last_mentioned_at: new Date(Date.now() - 518400000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 11232000000).toISOString(),
    ever_market_moving: 1,
  },
  {
    ticker: 'DIS',
    company_name: 'Walt Disney Co',
    sector: 'Consumer',
    total_mentions: 3,
    positive_count: 0,
    negative_count: 3,
    neutral_count: 0,
    avg_confidence: 0.78,
    avg_24h_move: -1.1,
    avg_1h_move: -0.5,
    last_mentioned_at: new Date(Date.now() - 432000000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 12096000000).toISOString(),
    ever_market_moving: 0,
  },
  {
    ticker: 'JPM',
    company_name: 'JPMorgan Chase',
    sector: 'Finance',
    total_mentions: 2,
    positive_count: 0,
    negative_count: 0,
    neutral_count: 2,
    avg_confidence: 0.85,
    avg_24h_move: 0.1,
    avg_1h_move: 0.0,
    last_mentioned_at: new Date(Date.now() - 345600000).toISOString(),
    first_mentioned_at: new Date(Date.now() - 12960000000).toISOString(),
    ever_market_moving: 0,
  },
]

export const MOCK_TRUMP_STATS = {
  totalMentions: 54,
  mentionsToday: 3,
  tickersTracked: 18,
  avgMarketMove: 1.62,
  biggestMover: { ticker: 'X', pct: 7.24 },
  lastCheckedAt: new Date().toISOString(),
}
